Make DL SWIG 1.3.40
datalogics/conan-center-index pull request #5
Opened 2021-05-24 16:17 UTC by datalogics-kam

Applied to a fork of CCI.

Make a recipe that we can use for SWIG 1.3.40 from our modified sources.

2021-05-24 21:14 UTC, datalogics-robb commented on recipes/swig/all/conanfile.py
> +            "--disable-dependency-checking",
Should this be `--diable-dependency-tracking`?  That would be what you'd use for an Automake configure script.

2021-05-24 21:17 UTC, datalogics-kam commented on recipes/swig/all/conanfile.py
> +            "--disable-dependency-checking",
Thanks. Good catch. Fixed it...that should help Windows.

2021-05-25 19:23 UTC, datalogics-kam commented
Note: There are changes to SWIG at CCI that just went up today...and I really don't want to pick them up yet. I know this works, and I think I tried updating automake and it broke something.

Remember that they're working with SWIG 4, and this is SWIG 1.3.40, and it might be a little touchy.

2021-05-25 20:10 UTC, datalogics-robb requested changes

2021-05-25 20:10 UTC, datalogics-robb commented on recipes/swig/all/conanfile.py
> +        git.clone('git@octocat.dlogics.com:datalogics/swig.git', branch='master')
I am finding this untestable, as it doesn't seem like `branch='master'` can be patched with the attached patch.

```
swig/1.3.40@datalogics/stable: Configuring sources in /home/robb/.conan/data/swig/1.3.40/datalogics/stable/source
swig/1.3.40@datalogics/stable: Copying sources to build folder
swig/1.3.40@datalogics/stable: Building your package in /home/robb/.conan/data/swig/1.3.40/datalogics/stable/build/f14d68b08b38b88e17811d2667d28ba7737af5fe
swig/1.3.40@datalogics/stable: Generator txt created conanbuildinfo.txt
swig/1.3.40@datalogics/stable: Calling build()
patches/0003-1.3.40-do-not-define-SWIG_LIB_WIN_UNIX.patch: premature end of source file b'configure.in' at hunk 1
patches/0003-1.3.40-do-not-define-SWIG_LIB_WIN_UNIX.patch: source file is different - b'configure.in'
swig/1.3.40@datalogics/stable: 
swig/1.3.40@datalogics/stable: ERROR: Package 'f14d68b08b38b88e17811d2667d28ba7737af5fe' build failed
swig/1.3.40@datalogics/stable: WARN: Build folder /home/robb/.conan/data/swig/1.3.40/datalogics/stable/build/f14d68b08b38b88e17811d2667d28ba7737af5fe
ERROR: swig/1.3.40@datalogics/stable: Error in build() method, line 115
	self._patch_sources()
while calling '_patch_sources', line 112
	tools.patch(**patch)
	ConanException: Failed to apply patch: patches/0003-1.3.40-do-not-define-SWIG_LIB_WIN_UNIX.patch
(python-env-foosa) robb@foosa:/raid/proj/procyon/checkouts-procyon/robb/dle-sandbox/conan-center-index/recipes/swig/all (make-dl-swig-1.3.40)$ 
```

2021-05-25 20:32 UTC, datalogics-kam commented
The `test_package` not working is a known problem. It's not modified from the one at Conan Center, and seems to want a particular Python. It even has comments that it doesn't work on Windows.

2021-05-25 20:34 UTC, datalogics-kam commented on recipes/swig/all/conanfile.py
> +        git.clone('git@octocat.dlogics.com:datalogics/swig.git', branch='master')
Works on my Mac and on rhel6 like below for instance:

```
conan create recipes/swig/all swig/1.3.40@kam/testing -pr devtoolset-7 --build missing
```

I suspect it's environmental. Try getting the Conan cache off of a remote filesystem.

The only change from "can build DLE on every platform" was pretty much the branch name.

2021-05-25 21:21 UTC, datalogics-robb commented on recipes/swig/all/conanfile.py
> +    settings = "os", "arch", "compiler", "build_type", "os_build", "arch_build"
Conan doesn't like this:
```
conan create  --build=missing -v -pr aix-xlc16-ppc . swig/1.3.40@datalogics/stable
************************************************************
  This package defines both 'os' and 'os_build' 
  Please use 'os' for libraries and 'os_build'
  only for build-requires used for cross-building
************************************************************
Exporting package recipe
```

2021-05-25 21:24 UTC, datalogics-kam commented on recipes/swig/all/conanfile.py
> +    settings = "os", "arch", "compiler", "build_type", "os_build", "arch_build"
It complains, but it works. Also, this is a program that's build-required for cross-building, so it's not that critical.

Those `_build` options are deleted from the package ID, but they have to be declared for the compatible settings.

This will be a lot better when we can use build profiles, which are pretty much the desired solution.

2021-05-25 21:42 UTC, datalogics-robb commented on recipes/swig/all/conanfile.py
> +        git.clone('git@octocat.dlogics.com:datalogics/swig.git', branch='master')
Tried clearing the cache of swig, then building on other machines, and all seems to go well up until the test package.
The arm box where I saw this error has seized up so I can't re-test that one.  Seems like it was an issue with the cache.

2021-05-25 22:34 UTC, datalogics-kam commented
@datalogics-robb Does this PR need something more from me?

2021-05-26 13:43 UTC, datalogics-kam commented
I'm working on making the test_package succeed...SWIG 1.3.40 is too old to build code for a modern Python, but I can still have it see that it built a running executable.

2021-05-26 15:14 UTC, datalogics-robb approved these changes

2021-05-26 15:14 UTC, merged